INSERT INTO `items` (`item`, `label`, `limit`, `can_remove`, `type`, `usable`, `groupId`, `desc`, `weight`) VALUES ('agarita', 'Agarita', -1, 1, 'item_standard', 1, 11, '', 0.01);
INSERT INTO `items` (`item`, `label`, `limit`, `can_remove`, `type`, `usable`, `groupId`, `desc`, `weight`) VALUES ('alaskanginseng', 'Alaskan Ginseng', -1, 1, 'item_standard', 1, 11, '', 0.01);
INSERT INTO `items` (`item`, `label`, `limit`, `can_remove`, `type`, `usable`, `groupId`, `desc`, `weight`) VALUES ('americanginseng', 'American Ginseng', -1, 1, 'item_standard', 1, 11, '', 0.01);
INSERT INTO `items` (`item`, `label`, `limit`, `can_remove`, `type`, `usable`, `groupId`, `desc`, `weight`) VALUES ('baybolete', 'Bay Bolete', -1, 1, 'item_standard', 1, 11, '', 0.01);
INSERT INTO `items` (`item`, `label`, `limit`, `can_remove`, `type`, `usable`, `groupId`, `desc`, `weight`) VALUES ('bitterweed', 'Bitterweed', -1, 1, 'item_standard', 1, 11, '', 0.01);
INSERT INTO `items` (`item`, `label`, `limit`, `can_remove`, `type`, `usable`, `groupId`, `desc`, `weight`) VALUES ('blackberry', 'Black Berry', -1, 1, 'item_standard', 1, 11, '', 0.01);
INSERT INTO `items` (`item`, `label`, `limit`, `can_remove`, `type`, `usable`, `groupId`, `desc`, `weight`) VALUES ('blackcurrant', 'Black Currant', -1, 1, 'item_standard', 1, 11, '', 0.01);
INSERT INTO `items` (`item`, `label`, `limit`, `can_remove`, `type`, `usable`, `groupId`, `desc`, `weight`) VALUES ('bloodflower', 'Blood Flower', -1, 1, 'item_standard', 1, 11, '', 0.01);
INSERT INTO `items` (`item`, `label`, `limit`, `can_remove`, `type`, `usable`, `groupId`, `desc`, `weight`) VALUES ('burdockroot', 'Burdock Root', -1, 1, 'item_standard', 1, 11, '', 0.01);
INSERT INTO `items` (`item`, `label`, `limit`, `can_remove`, `type`, `usable`, `groupId`, `desc`, `weight`) VALUES ('cardinalflower', 'Cardinal Flower', -1, 1, 'item_standard', 1, 11, '', 0.01);
INSERT INTO `items` (`item`, `label`, `limit`, `can_remove`, `type`, `usable`, `groupId`, `desc`, `weight`) VALUES ('chanterelle', 'Chanterelle', -1, 1, 'item_standard', 1, 11, '', 0.01);
INSERT INTO `items` (`item`, `label`, `limit`, `can_remove`, `type`, `usable`, `groupId`, `desc`, `weight`) VALUES ('chocolatedaisy', 'Chocolate Daisy', -1, 1, 'item_standard', 1, 11, '', 0.01);
INSERT INTO `items` (`item`, `label`, `limit`, `can_remove`, `type`, `usable`, `groupId`, `desc`, `weight`) VALUES ('commonbulrush', 'Common Bulrush', -1, 1, 'item_standard', 1, 11, '', 0.01);
INSERT INTO `items` (`item`, `label`, `limit`, `can_remove`, `type`, `usable`, `groupId`, `desc`, `weight`) VALUES ('creekplum', 'Creek Plum', -1, 1, 'item_standard', 1, 11, '', 0.01);
INSERT INTO `items` (`item`, `label`, `limit`, `can_remove`, `type`, `usable`, `groupId`, `desc`, `weight`) VALUES ('creepingthyme', 'Creeping Thyme', -1, 1, 'item_standard', 1, 11, '', 0.01);
INSERT INTO `items` (`item`, `label`, `limit`, `can_remove`, `type`, `usable`, `groupId`, `desc`, `weight`) VALUES ('crowsgarlic', 'Crows Garlic', -1, 1, 'item_standard', 1, 11, '', 0.01);
INSERT INTO `items` (`item`, `label`, `limit`, `can_remove`, `type`, `usable`, `groupId`, `desc`, `weight`) VALUES ('desertsage', 'Desert Sage', -1, 1, 'item_standard', 1, 11, '', 0.01);
INSERT INTO `items` (`item`, `label`, `limit`, `can_remove`, `type`, `usable`, `groupId`, `desc`, `weight`) VALUES ('englishmace', 'English Mace', -1, 1, 'item_standard', 1, 11, '', 0.01);
INSERT INTO `items` (`item`, `label`, `limit`, `can_remove`, `type`, `usable`, `groupId`, `desc`, `weight`) VALUES ('evergreenhuckleberry', 'Evergreen Huckleberry', -1, 1, 'item_standard', 1, 11, '', 0.01);
INSERT INTO `items` (`item`, `label`, `limit`, `can_remove`, `type`, `usable`, `groupId`, `desc`, `weight`) VALUES ('goldencurrant', 'Golden Currant', -1, 1, 'item_standard', 1, 11, '', 0.01);
INSERT INTO `items` (`item`, `label`, `limit`, `can_remove`, `type`, `usable`, `groupId`, `desc`, `weight`) VALUES ('harrietumofficinalis', 'Harrietum Officinalis', -1, 1, 'item_standard', 1, 11, '', 0.01);
INSERT INTO `items` (`item`, `label`, `limit`, `can_remove`, `type`, `usable`, `groupId`, `desc`, `weight`) VALUES ('hummingbirdsage', 'Hummingbird Sage', -1, 1, 'item_standard', 1, 11, '', 0.01);
INSERT INTO `items` (`item`, `label`, `limit`, `can_remove`, `type`, `usable`, `groupId`, `desc`, `weight`) VALUES ('indiantobacco', 'Indian Tobacco', -1, 1, 'item_standard', 1, 11, '', 0.01);
INSERT INTO `items` (`item`, `label`, `limit`, `can_remove`, `type`, `usable`, `groupId`, `desc`, `weight`) VALUES ('milkweed', 'Milkweed', -1, 1, 'item_standard', 1, 11, '', 0.01);
INSERT INTO `items` (`item`, `label`, `limit`, `can_remove`, `type`, `usable`, `groupId`, `desc`, `weight`) VALUES ('oleandersage', 'Oleander Sage', -1, 1, 'item_standard', 1, 11, '', 0.01);
INSERT INTO `items` (`item`, `label`, `limit`, `can_remove`, `type`, `usable`, `groupId`, `desc`, `weight`) VALUES ('oregano', 'Oregano', -1, 1, 'item_standard', 1, 11, '', 0.01);
INSERT INTO `items` (`item`, `label`, `limit`, `can_remove`, `type`, `usable`, `groupId`, `desc`, `weight`) VALUES ('parasolmushroom', 'Parasol Mushroom', -1, 1, 'item_standard', 1, 11, '', 0.01);
INSERT INTO `items` (`item`, `label`, `limit`, `can_remove`, `type`, `usable`, `groupId`, `desc`, `weight`) VALUES ('prairiepoppy', 'Prairie Poppy', -1, 1, 'item_standard', 1, 11, '', 0.01);
INSERT INTO `items` (`item`, `label`, `limit`, `can_remove`, `type`, `usable`, `groupId`, `desc`, `weight`) VALUES ('ramshead', 'Rams Head', -1, 1, 'item_standard', 1, 11, '', 0.01);
INSERT INTO `items` (`item`, `label`, `limit`, `can_remove`, `type`, `usable`, `groupId`, `desc`, `weight`) VALUES ('redraspberry', 'Red Raspberry', -1, 1, 'item_standard', 1, 11, '', 0.01);
INSERT INTO `items` (`item`, `label`, `limit`, `can_remove`, `type`, `usable`, `groupId`, `desc`, `weight`) VALUES ('redsage', 'Red Sage', -1, 1, 'item_standard', 1, 11, '', 0.01);
INSERT INTO `items` (`item`, `label`, `limit`, `can_remove`, `type`, `usable`, `groupId`, `desc`, `weight`) VALUES ('saltbush', 'Saltbush', -1, 1, 'item_standard', 1, 11, '', 0.01);
INSERT INTO `items` (`item`, `label`, `limit`, `can_remove`, `type`, `usable`, `groupId`, `desc`, `weight`) VALUES ('texasbluebonnet', 'Texas Blue Bonnet', -1, 1, 'item_standard', 1, 11, '', 0.01);
INSERT INTO `items` (`item`, `label`, `limit`, `can_remove`, `type`, `usable`, `groupId`, `desc`, `weight`) VALUES ('violetsnowdrop', 'Violet Snowdrop', -1, 1, 'item_standard', 1, 11, '', 0.01);
INSERT INTO `items` (`item`, `label`, `limit`, `can_remove`, `type`, `usable`, `groupId`, `desc`, `weight`) VALUES ('wildcarrot', 'Wild Carrot', -1, 1, 'item_standard', 1, 11, '', 0.01);
INSERT INTO `items` (`item`, `label`, `limit`, `can_remove`, `type`, `usable`, `groupId`, `desc`, `weight`) VALUES ('wildfeverfew', 'Wild Feverfew', -1, 1, 'item_standard', 1, 11, '', 0.01);
INSERT INTO `items` (`item`, `label`, `limit`, `can_remove`, `type`, `usable`, `groupId`, `desc`, `weight`) VALUES ('wildmint', 'Wild Mint', -1, 1, 'item_standard', 1, 11, '', 0.01);
INSERT INTO `items` (`item`, `label`, `limit`, `can_remove`, `type`, `usable`, `groupId`, `desc`, `weight`) VALUES ('wildrhubarb', 'Wild Rhubarb', -1, 1, 'item_standard', 1, 11, '', 0.01);
INSERT INTO `items` (`item`, `label`, `limit`, `can_remove`, `type`, `usable`, `groupId`, `desc`, `weight`) VALUES ('wintergreenberry', 'Wintergreen Berry', -1, 1, 'item_standard', 1, 11, '', 0.01);
INSERT INTO `items` (`item`, `label`, `limit`, `can_remove`, `type`, `usable`, `groupId`, `desc`, `weight`) VALUES ('wisteria', 'Wisteria', -1, 1, 'item_standard', 1, 11, '', 0.01);
INSERT INTO `items` (`item`, `label`, `limit`, `can_remove`, `type`, `usable`, `groupId`, `desc`, `weight`) VALUES ('yarrow', 'Yarrow', -1, 1, 'item_standard', 1, 11, '', 0.01);
